version: "3.11"


services:

  app:
    build: ./src
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - RABBIT_HOST=rabbitmq
    command: ["python", "-m", "src"]
    volumes:
      - ./src:/usr/src/src
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis

  db:
    image: "postgres:latest"
    ports:
      - 5666:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

